### PR TITLE
Refactoring/jms refactoring

### PR DESCRIPTION
**Pull request by ankovi**

### CODE REVIEW

**Review by ebrygg — CHANGES_REQUESTED** [review]
No dependencies on snapshots
 <uvms.common.version>3.0.18-SNAPSHOT</uvms.common.version>

**Comment by ankovi** [comment]
@ebrygg 
Can you please explain a bit better the why of "No SNAPSHOT dependencies" "policy"?

**Comment by ebrygg** [comment]
We do not use SNAPSHOTs from other projects (external or internal) since they are changing constantly by definition. This makes it impossible to have any type of regression.

**Comment by ankovi** [comment]
test me

**Comment by ankovi** [comment]
test me

**Comment by ankovi** [comment]
test me

**Review by ebrygg — APPROVED** [review]
ok!

**Pull request merged**
